language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
script: 
- 'export PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} && 
  bundle exec pronto run -f github_pr' &&
  bundle exec rspec spec
GITHUB_ACCESS_TOKEN: ef2f1a991d20d907620952322fc68afeb201af48
before_script:
- psql -c 'create database church_dashboard_qa;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: FJq3VuGesbkscbpiFLNWW2twyjsC77c55A7XxsJrjoOXfJmCl9kjBYmK6jjOsmEog7Hww+fv2JK0vCGtKRdSr35gGUlmYdGgWh+umz88gw/kfVHAHDlTfquiprHDzqcHRcQoGfy1C9rDEjof8S32cClisIAJ0862McK2/m9NHEQ=
  app: church-dashboard
  on:
    repo: bdeverea/Church-Dashboard
before_script: 
  - 'rake db:test:prepare'
  - 'rake db:migrate'